import React from 'react';
import { 
  Crosshair, 
  GitCompare, 
  Layers, 
  Sliders, 
  Activity, 
  FileCheck, 
  ShieldCheck, 
  CheckCircle2, 
  Cpu
} from 'lucide-react';

export const EvidenceGroundedSection: React.FC = () => {
  const evidenceTypes = [
    {
      icon: Crosshair,
      title: 'Highlighted Regions & Masks',
      description: 'Pixel-level segmentation masks overlaying exact geographical boundaries, allowing zero-ambiguity visual verification of detected features.'
    },
    {
      icon: Crosshair,
      title: 'Bounding Boxes & Coordinates',
      description: 'Strict spatial bounding boxes with georeferenced bounding envelope coordinates (WGS84 EPSG:4326 / UTM) and individual confidence values.'
    },
    {
      icon: GitCompare,
      title: 'Multi-Temporal Change Maps',
      description: 'Color-coded difference heatmaps showing exact gain, loss, and unchanged land cover between historical baselines and current passes.'
    },
    {
      icon: Sliders,
      title: 'Before / After Comparisons',
      description: 'Interactive swipe-dividers and side-by-side inspection panes allowing immediate visual corroboration across multiple spectral bands.'
    },
    {
      icon: Activity,
      title: 'Calibrated Confidence Scores',
      description: 'Probabilistic confidence ratings generated by model ensemble verification rather than ungrounded hallucination.'
    },
    {
      icon: FileCheck,
      title: 'Transparent Execution Summaries',
      description: 'Full audit traces showing the exact specialist models dispatched, processing pipeline stages, and inference latency.'
    }
  ];

  return (
    <section className="py-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto border-b border-slate-200/80 dark:border-slate-800/80">
      {/* Header */}
      <div className="text-center max-w-3xl mx-auto mb-16 space-y-3">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 font-mono text-xs font-semibold uppercase tracking-wider">
          <ShieldCheck className="w-3.5 h-3.5 text-cyan-500" />
          Verifiable Scientific AI
        </div>
        <h2 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
          Don't Just Get an Answer. See the Evidence.
        </h2>
        <p className="text-slate-600 dark:text-slate-300 text-sm sm:text-base leading-relaxed">
          Generic language models hallucinate. SatQuery AI grounds every textual answer in verifiable spatial evidence, multi-spectral band mathematics, and reproducible execution traces.
        </p>
      </div>

      {/* Grid: 6 Evidence Pillars with Visual Satellite Demonstration */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
        {/* Left 6 cols: Visual Evidence Demonstration */}
        <div className="lg:col-span-6 space-y-4">
          <div 
            className="h-80 sm:h-96 rounded-2xl relative overflow-hidden border-2 border-cyan-400/50 p-6 flex flex-col justify-between shadow-2xl shadow-cyan-500/10"
            style={{ background: 'linear-gradient(135deg, #0f172a 0%, #134e4a 35%, #0284c7 70%, #1e293b 100%)' }}
          >
            <div className="absolute inset-0 geo-grid-pattern opacity-40 pointer-events-none" />

            {/* Top HUD Overlay */}
            <div className="relative z-10 flex items-center justify-between text-xs font-mono text-white">
              <span className="px-2.5 py-1 rounded bg-slate-950/80 border border-slate-700/80 font-bold backdrop-blur-xs">
                Sentinel-2 L2A BOA • Surface Reflectance
              </span>
              <span className="px-2.5 py-1 rounded bg-cyan-950/80 border border-cyan-400/50 text-cyan-300 font-bold backdrop-blur-xs">
                IoU: 94.8% Verified
              </span>
            </div>

            {/* Highlighted Bounding Box 1 */}
            <div className="absolute top-16 left-12 w-48 h-36 border-2 border-dashed border-cyan-400 rounded-xl bg-cyan-400/10 pointer-events-none p-2 flex flex-col justify-between">
              <span className="text-[10px] font-mono font-bold text-cyan-300 bg-slate-950/80 px-1.5 py-0.5 rounded self-start">
                Reservoir Perimeter [Class: Open Water]
              </span>
              <span className="text-[9px] font-mono text-cyan-200 self-end">
                NDWI: +0.68
              </span>
            </div>

            {/* Highlighted Bounding Box 2 */}
            <div className="absolute bottom-16 right-10 w-40 h-28 border-2 border-dashed border-teal-400 rounded-xl bg-teal-400/10 pointer-events-none p-2 flex flex-col justify-between">
              <span className="text-[10px] font-mono font-bold text-teal-300 bg-slate-950/80 px-1.5 py-0.5 rounded self-start">
                Spillway Channel
              </span>
              <span className="text-[9px] font-mono text-teal-200 self-end">
                Conf: 96.2%
              </span>
            </div>

            {/* Bottom Telemetry Bar */}
            <div className="relative z-10 p-3 rounded-xl bg-slate-950/90 border border-slate-700/80 text-xs font-mono text-slate-300 backdrop-blur-sm flex items-center justify-between">
              <span>Projection: EPSG:32644 [WGS84 UTM Zone 44N]</span>
              <span className="text-cyan-400 font-bold">100% Traceable</span>
            </div>
          </div>
        </div>

        {/* Right 6 cols: 6 Evidence Types (Section 9 of design.md) */}
        <div className="lg:col-span-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
          {evidenceTypes.map((item, idx) => {
            const Icon = item.icon;
            return (
              <div
                key={idx}
                className="p-4 rounded-xl bg-white dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 hover:border-cyan-500/30 transition-all shadow-xs"
              >
                <div className="w-8 h-8 rounded-lg bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 flex items-center justify-center mb-2.5">
                  <Icon className="w-4 h-4" />
                </div>
                <h4 className="text-xs font-bold text-slate-900 dark:text-white mb-1">
                  {item.title}
                </h4>
                <p className="text-[11px] text-slate-600 dark:text-slate-300 leading-relaxed">
                  {item.description}
                </p>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};
